CREATE TABLE "HELLO_WORLD" (
  "ID"               BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT
 ,"VERSION"          INTEGER      NOT NULL
 ,"VALUE"            VARCHAR(255)
 ,"CREATED_AT"       TIMESTAMP    NOT NULL
 ,"CREATED_BY"       VARCHAR(255) NOT NULL
 ,"LAST_MODIFIED_AT" TIMESTAMP
 ,"LAST_MODIFIED_BY" VARCHAR(255)
);
