security:
  oauth2:
    client:
      client-id: rest
      client-secret: rest
spring:
  datasource:
    url: jdbc:h2:mem:oauth2-example
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-zone-id: true
      indent-output: true
    generator:
      write-bigdecimal-as-plain: true
owncloud:
  location: classpath:/owncloud.xml
