server:
  session:
    cookie:
      name: EXAMPLESESSION
spring:
  aop:
    proxy-target-class: true # without this the Security wont work in conjunction with the GetMapping
  datasource:
    url: jdbc:h2:mem:angular2-example
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
#    properties:
#      hibernate.format_sql: true
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-zone-id: true
      indent-output: true
    generator:
      write-bigdecimal-as-plain: true
  thymeleaf:
    prefix: classpath:/META-INF/resources/frontend/
    mode: HTML
owncloud:
  location: classpath:/owncloud.xml
info:
  build:
    version: "@project.version@"
