CREATE TABLE "OAUTH_ACCESS_TOKEN" (
  "TOKEN_ID"          VARCHAR(255)
 ,"TOKEN"             BLOB
 ,"AUTHENTICATION_ID" VARCHAR(255) PRIMARY KEY
 ,"USER_NAME"         VARCHAR(255)
 ,"CLIENT_ID"         VARCHAR(255)
 ,"AUTHENTICATION"    BLOB
 ,"REFRESH_TOKEN"     VARCHAR(255)
);

CREATE TABLE "OAUTH_REFRESH_TOKEN" (
  "TOKEN_ID"       VARCHAR(255)
 ,"TOKEN"          BLOB
 ,"AUTHENTICATION" BLOB
);
